### ISSUE TITLE
Some problems and suggestions for improvement.

### ISSUE THREAD

**Issue by simonpuchert** [ykallus/SofaBounds#1]
1. Compilation with newer versions of Boost (tested with 1.70) fails. This is easily fixed by replacing
 - `x.mpq()` with `x.backend().data()` in `rat_str`,
 - `x.numerator()` and `x.denominator()` with `numerator(x)` and `denominator(x)` in `ell_side`,
both functions are in `sofa-bounds.cpp`.
2. The bounds in `a_priori_bounds` for the case `\beta = \pi / 2` are wrong, in particular,
`x1 = -c / a` should be `x1 = -c / a - c^2 / (ab) = -c/a - a/b - b/a`. This seems to be a mistake in the paper, which can be seen by setting `\alpha = \pi / 4`, leading to the bounds `[-\sqrt{2}, \sqrt{2}]` instead of the correct `[-2 - \sqrt{2}, \sqrt{2}]`.
3. There are some easy speed-ups, e.g. in `rotated_ell`, reusing the faces seemed best:
```c++
    default:
-        N1 = ell_side(myslope,xb,0,0,0,0).intersection(ell_side(myslope,xb,0,1,1,1)).intersection(ell_side(myslope,yb,1,1,1,1)); //left arm
-        N2 = ell_side(myslope,yb,1,0,0,0).intersection(ell_side(myslope,yb,1,1,1,1)).intersection(ell_side(myslope,xb,0,1,1,1)); //right arm
-        return N1.join(N2);
+        N1 = ell_side(myslope,xb,0,1,1,1).intersection(ell_side(myslope,yb,1,1,1,1)); //outer corner
+        N2 = ell_side(myslope,xb,0,0,0,0).join(ell_side(myslope,yb,1,0,0,0)); //inner corner
+        return N1.intersection(N2);
```
4. Another improvement: The splitting index is selected to maximize the intersection of the current union with a certain region. This region currently does not mean much (is that a bug?). In experiments (mostly with `thm9-bound1.txt`) I found that the maximizing the "lost area", i.e. `A - A_1 + A - A_2` was somewhat better. This can be optimized further by leaving out some faces that are not required because of the intersection with the union (6 faces -> 3 faces).

I can submit pull requests for these points, but I will have to straighten out some whitespace shenanigans first.

**Comment by ykallus** [comment]
Thank you for finding these problems and for your suggestions for improvement. Pull requests to address them would be very welcome.

**Comment by simonpuchert** [comment]
Some more observations:

To fill the gap between a (possibly erroneous) proof and the "real" proof, one would only have to consider the set difference between the (correct / incorrect) intervals, leading to a much quicker computation than re-running the entire thing. I suspect that the branch-and-bound algorithm will make short work of this set difference, since it's far from the optimal configuration.

Concerning the boost / CGAL compatibility: I tested this on another machine and it seems
- CGAL 4.12, Boost 1.66 only works with the current code
- CGAL 4.14, Boost 1.70 only works with the modified code (and spews out some warnings about deprecated Boost functions that seem to be CGAL's fault).

This is unfortunate, but since the (small) modification is here for future reference, it's not a big deal.

I've also drafted a proof of the conjecture that an optimal moving sofa must rotate by an angle of exactly π/2 and sent it to D. Romik.

**Comment by ykallus** [comment]
Points 2 and 3 resolved by #2. Point 1 related to library versions not fixed, but #3 adds note in README with recommended versions. Point 4 not resolved and it's possible a different splitting rule might lead to significant speed up.

**Comment by lczyk** [comment]
In case anyone if working with this project in newer version of coal and boost; for CGAL 5.2.1 and Boost 1.75.0 the `x.numerator()` and `x.denominator()` become `x.get_num()` and `xget_den()`, while the entire `rat_str` function can be replaced by `x.get_str()`.

**Comment by lczyk** [comment]
Also, here is my `CMakeLists.txt` for this project. Might come in useful to someone.

```cmake
cmake_minimum_required(VERSION 3.12)
project(sofabounds)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

set(CMAKE_CXX_FLAGS "-O3 -Wall -Wfatal-errors")
set(CMAKE_BUILD_TYPE "Release")

set(SOURCES
    sofa-bounds.cpp
    branch-and-bound.cpp
    frontend.cpp
    )
    
find_package(CGAL REQUIRED)
add_executable(sofabounds ${SOURCES})
target_link_libraries(sofabounds LINK_PUBLIC ${CGAL_LIBRARIES} )
target_include_directories(sofabounds PUBLIC .)
```

**Comment by MrBrain295** [comment]
It would also be useful if this could store the search state so that long runs can be safe in the case of crashes or power outages.
